version: '3.8'

services:
  # Python Paper Processor Service
  paper-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-paper-processor
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_PAPERS_PREFIX=${S3_PAPERS_PREFIX}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CONFLUENCE_URL=${CONFLUENCE_URL}
      - CONFLUENCE_EMAIL=${CONFLUENCE_EMAIL}
      - CONFLUENCE_API_TOKEN=${CONFLUENCE_API_TOKEN}
      - CONFLUENCE_SPACE_KEY=${CONFLUENCE_SPACE_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # n8n Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-changeme}
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Seoul
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_PAPERS_PREFIX=${S3_PAPERS_PREFIX}
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_workflow.json:/workflows/ai_paper_newsletter.json:ro
    restart: unless-stopped
    depends_on:
      paper-processor:
        condition: service_healthy

volumes:
  n8n_data:
    driver: local

networks:
  default:
    name: ai-paper-network